spring:
  main:
    web-application-type: none
  mail:
    host: localhost
    port: 25
    protocol: smtp

#Logging configuration
logging:
  level:
    ROOT: INFO
    cucumber: TRACE
    com.nortal.test: INFO
    org.springframework: INFO
    org.springframework.jdbc: DEBUG

#Test automation configuration
test-automation:
  settings:
    use-default-bridge-network: true
  scenario:
    scope: MOCKED
    domain: DEFAULT
  integration:
    jdbc:
      driverClassName: org.postgresql.Driver
      url: dynamically-set-from-testcontainers
      username: postgres
      password: postgres
    http:
      connection-time-out: 30
    hosts:
      project-api: http://localhost:1000/project-api
  containers:
    postgre:
      enabled: true
    mock-server:
      enabled: true
      aliases:
        - aclapi
        - inventoryapi
    testable-container:
      base-image: openjdk:11-slim
      jar-build-dir: ../app-main/build/libs
      debug-port: 9000
      jacoco:
        enabled: true
      wait-for-debugger: false
  report:
    enabled: true
    capabilities: "@Palladium,@Rhodium"
    mail:
      enabled: false
      from: no-reply@nortal-test.com
      to: |-
        ricardas.buciunas@nortal.com
